<a href="https://colab.research.google.com/github/BrionesC/Cardiocotografia/blob/main/Cardiocotograf%C3%ADa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Briones Coello Doménica Nicole

**Práctica de Cardiocotografía**

In [ ]:
#RANDOM_STATE DE 1-100
#TEST_SIZE DE 80/20 70/30
#ENTRENAR EL MODELO CON svm, knn, LR, random forest, arboles de decisión.
#acurracy de cada uno
#matriz de confusión

In [ ]:
!pip install pingouin==0.5.2

Collecting pingouin==0.5.2
  Downloading pingouin-0.5.2.tar.gz (185 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.4/185.4 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (1.25.2)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (1.11.4)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (2.0.3)
Requirement already satisfied: matplotlib>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (3.7.1)
Requirement already satisfied: seaborn>=0.11 in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (0.13.1)
Requirement already satisfied: statsmodels>=0.13 in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (0.14.2)
Collecting scikit-learn<1.1.0 (from pingouin==0.5.2)
  Downloading scikit_learn-1.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 46.6 MB/s eta 0:00:00
Collecting pandas_flavor>=0.2.0 (from pingouin==0.5.2)
  Downloading pandas_flavor-0.6.0-py3-none-any.whl (7.2 kB)
Collecting outdated (from pingouin==0.5.2)
  Downloading outdated-0.2.2-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from pingouin==0.5.2) (0.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin==0.5.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->pingouin==0.5.2) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->pingouin==0.5.2) (2024.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (from pandas_flavor>=0.2.0->pingouin==0.5.2) (2023.7.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<1.1.0->pingouin==0.5.2) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<1.1.0->pingouin==0.5.2) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.13->pingouin==0.5.2) (0.5.6)
Requirement already satisfied: setuptools>=44 in /usr/local/lib/python3.10/dist-packages (from outdated->pingouin==0.5.2) (67.7.2)
Collecting littleutils (from outdated->pingouin==0.5.2)
  Downloading littleutils-0.2.4-py3-none-any.whl (8.1 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from outdated->pingouin==0.5.2) (2.31.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels>=0.13->pingouin==0.5.2) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin==0.5.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin==0.5.2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin==0.5.2) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin==0.5.2) (2024.7.4)
Building wheels for collected packages: pingouin
  Building wheel for pingouin (setup.py) ... done
  Created wheel for pingouin: filename=pingouin-0.5.2-py3-none-any.whl size=196188 sha256=c90684db42fe7d5715525a2ab91e7c96f1f079f84697d6e4cdfc31cc2de6473e
  Stored in directory: /root/.cache/pip/wheels/1f/bb/0c/2bdd36d8a6d74b17b4622927fd78da815f0988dfcfa8b1fa45
Successfully built pingouin
Installing collected packages: littleutils, scikit-learn, outdated, pandas_flavor, pingouin
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 1.11.1 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.
Successfully installed littleutils-0.2.4 outdated-0.2.2 pandas_flavor-0.6.0 pingouin-0.5.2 scikit-learn-1.0.2

In [ ]:
import pandas as pd
import numpy as np
import pingouin as pg
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [ ]:
# Verificar la versión de pandas
print("Versión de pandas:", pd.__version__)

Versión de pandas: 2.0.3

In [ ]:
#Leer el archivo CTG(1).xls

import pandas as pd

#df = pd.read_excel("/content/CTG (1).xls", sheet_name='Raw Data')

df = pd.ExcelFile('/content/CTG (1).xls')
#data= pd.read_excel(xls)

sheet_name = 'Raw Data'
data = pd.read_excel(df, sheet_name=sheet_name)

In [ ]:
data.head()

,FileName,Date,SegFile,b,e,LBE,LB,AC,FM,UC,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Variab10.txt,1996-12-01,CTG0001.txt,240.0,357.0,120.0,120.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,2.0
2,Fmcs_1.txt,1996-05-03,CTG0002.txt,5.0,632.0,132.0,132.0,4.0,0.0,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
3,Fmcs_1.txt,1996-05-03,CTG0003.txt,177.0,779.0,133.0,133.0,2.0,0.0,5.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
4,Fmcs_1.txt,1996-05-03,CTG0004.txt,411.0,1192.0,134.0,134.0,2.0,0.0,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0

In [ ]:
data.tail()

,FileName,Date,SegFile,b,e,LBE,LB,AC,FM,UC,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
2125,S8001045.dsp,1998-06-06,CTG2127.txt,1576.0,3049.0,140.0,140.0,1.0,0.0,9.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,2.0
2126,S8001045.dsp,1998-06-06,CTG2128.txt,2796.0,3415.0,142.0,142.0,1.0,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
2127,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2128,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2129,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,564.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.shape

(2130, 40)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2130 entries, 0 to 2129
Data columns (total 40 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FileName  2126 non-null   object
 1   Date      2126 non-null   datetime64[ns]
 2   SegFile   2126 non-null   object
 3   b         2126 non-null   float64
 4   e         2126 non-null   float64
 5   LBE       2126 non-null   float64
 6   LB        2126 non-null   float64
 7   AC        2126 non-null   float64
 8   FM        2127 non-null   float64
 9   UC        2127 non-null   float64
 10  ASTV      2127 non-null   float64
 11  MSTV      2127 non-null   float64
 12  ALTV      2127 non-null   float64
 13  MLTV      2127 non-null   float64
 14  DL        2128 non-null   float64
 15  DS        2128 non-null   float64
 16  DP        2128 non-null   float64
 17  DR        2128 non-null   float64
 18  Width     2126 non-null   float64
 19  Min       2126 non-null   float64
 20  Max       2126 non-null   float64
 21  Nmax      2126 non-null   float64
 22  Nzeros    2126 non-null   float64
 23  Mode      2126 non-null   float64
 24  Mean      2126 non-null   float64
 25  Median    2126 non-null   float64
 26  Variance  2126 non-null   float64
 27  Tendency  2126 non-null   float64
 28  A         2126 non-null   float64
 29  B         2126 non-null   float64
 30  C         2126 non-null   float64
 31  D         2126 non-null   float64
 32  E         2126 non-null   float64
 33  AD        2126 non-null   float64
 34  DE        2126 non-null   float64
 35  LD        2126 non-null   float64
 36  FS        2126 non-null   float64
 37  SUSP      2126 non-null   float64
 38  CLASS     2126 non-null   float64
 39  NSP       2126 non-null   float64
dtypes: datetime64[ns](1), float64(37), object(2)
memory usage: 665.8+ KB

In [ ]:
# Verificar valores faltantes
print(data.isnull().sum())

# Manejar valores faltantes (si es necesario)
# data.fillna(method='ffill', inplace=True)

FileName    4
Date        4
SegFile     4
b           4
e           4
LBE         4
LB          4
AC          4
FM          3
UC          3
ASTV        3
MSTV        3
ALTV        3
MLTV        3
DL          2
DS          2
DP          2
DR          2
Width       4
Min         4
Max         4
Nmax        4
Nzeros      4
Mode        4
Mean        4
Median      4
Variance    4
Tendency    4
A           4
B           4
C           4
D           4
E           4
AD          4
DE          4
LD          4
FS          4
SUSP        4
CLASS       4
NSP         4
dtype: int64

In [ ]:
#3 eliminar columnas irrelevantes
dataset_rmvCOl = data.drop(columns=['FileName','SegFile', 'Date'])
dataset_rmvCOl.head()

,b,e,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,240.0,357.0,120.0,120.0,0.0,0.0,0.0,73.0,0.5,43.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,2.0
2,5.0,632.0,132.0,132.0,4.0,0.0,4.0,17.0,2.1,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
3,177.0,779.0,133.0,133.0,2.0,0.0,5.0,16.0,2.1,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
4,411.0,1192.0,134.0,134.0,2.0,0.0,6.0,16.0,2.4,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0

In [ ]:
#4 eliminar  valores nulos NaN
finaldata = dataset_rmvCOl.dropna()
finaldata.head()

,b,e,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
1,240.0,357.0,120.0,120.0,0.0,0.0,0.0,73.0,0.5,43.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,2.0
2,5.0,632.0,132.0,132.0,4.0,0.0,4.0,17.0,2.1,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
3,177.0,779.0,133.0,133.0,2.0,0.0,5.0,16.0,2.1,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
4,411.0,1192.0,134.0,134.0,2.0,0.0,6.0,16.0,2.4,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
5,533.0,1147.0,132.0,132.0,4.0,0.0,5.0,16.0,2.4,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0

In [ ]:
finaldata.shape

(2126, 37)

In [ ]:
# Paso 6. Dividir los datos en: Entrada X - variables/features/atributos; y, salida y - labels/etiquetas

# otra forma de hacerlo.
# Obtener las columnas desde la primera hasta la columna 35
xx = finaldata.columns[0:36]

# Seleccionar las columnas correspondientes en el DataFrame finaldata
x = finaldata[xx]

# Mostrar el DataFrame x
print(x)

           b       e    LBE     LB   AC   FM   UC  ASTV  MSTV  ALTV  ...    B  \
1      240.0   357.0  120.0  120.0  0.0  0.0  0.0  73.0   0.5  43.0  ...  0.0
2        5.0   632.0  132.0  132.0  4.0  0.0  4.0  17.0   2.1   0.0  ...  0.0
3      177.0   779.0  133.0  133.0  2.0  0.0  5.0  16.0   2.1   0.0  ...  0.0
4      411.0  1192.0  134.0  134.0  2.0  0.0  6.0  16.0   2.4   0.0  ...  0.0
5      533.0  1147.0  132.0  132.0  4.0  0.0  5.0  16.0   2.4   0.0  ...  1.0
...      ...     ...    ...    ...  ...  ...  ...   ...   ...   ...  ...  ...
2122  2059.0  2867.0  140.0  140.0  0.0  0.0  6.0  79.0   0.2  25.0  ...  0.0
2123  1576.0  2867.0  140.0  140.0  1.0  0.0  9.0  78.0   0.4  22.0  ...  0.0
2124  1576.0  2596.0  140.0  140.0  1.0  0.0  7.0  79.0   0.4  20.0  ...  0.0
2125  1576.0  3049.0  140.0  140.0  1.0  0.0  9.0  78.0   0.4  27.0  ...  0.0
2126  2796.0  3415.0  142.0  142.0  1.0  1.0  5.0  74.0   0.4  36.0  ...  0.0

        C    D    E   AD   DE   LD   FS  SUSP  CLASS
1     0.0  0.0  0.0  0.0  0.0  0.0  1.0   0.0    9.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0
3     0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0
4     0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0
5     0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    2.0
...   ...  ...  ...  ...  ...  ...  ...   ...    ...
2122  0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0    5.0
2123  0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0    5.0
2124  0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0    5.0
2125  0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0    5.0
2126  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    1.0

[2126 rows x 36 columns]

In [ ]:
# Obtener la columna en el índice 36 (columna 37 considerando índices base 0)
features1 = list(finaldata.columns[36:37])

# Seleccionar la columna correspondiente en el DataFrame finaldata
y = finaldata[features1]

# Mostrar el DataFrame y
print(y)

      NSP
1     2.0
2     1.0
3     1.0
4     1.0
5     1.0
...   ...
2122  2.0
2123  2.0
2124  2.0
2125  2.0
2126  1.0

[2126 rows x 1 columns]

In [ ]:
#Mostrar y
y

      NSP
1     2.0
2     1.0
3     1.0
4     1.0
5     1.0
...   ...
2122  2.0
2123  2.0
2124  2.0
2125  2.0
2126  1.0

[2126 rows x 1 columns]

In [ ]:
# Número aleatorio entre 1 y 100
random_state = np.random.randint(1, 101)

print(random_state)

92

#ENTRENAMIENTO CON SVM

In [ ]:
#ENTRENAR EL MODELO CON svm

# Dividir los datos en conjuntos de entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo SVM
svm_model = SVC()
svm_model.fit(X_train, y_train.values.ravel()) # Aplanar y_train usando ravel()

# Hacer predicciones en el conjunto de prueba
y_pred = svm_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (SVM):", accuracy)
print("Matriz de confusión (SVM):\n", conf_matrix)

Accuracy (SVM): 0.9859154929577465
Matriz de confusión (SVM):
 [[333   1   0]
 [  5  48   0]
 [  0   0  39]]

In [ ]:
#ENTRENAR EL MODELO CON SVM

# Dividir los datos en conjuntos de entrenamiento y prueba (70/30)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = svm_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (SVM):", accuracy)
print("Matriz de confusión (SVM):\n", conf_matrix)

Accuracy (SVM): 0.9796238244514106
Matriz de confusión (SVM):
 [[496   2   0]
 [ 11  73   0]
 [  0   0  56]]

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

#ENTRENAMIENTO CON KNN

In [ ]:
#ENTRENAR MODELO CON KNN

from sklearn.neighbors import KNeighborsClassifier

# Dividir los datos en conjuntos de entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo KNN (considera ajustar el número de vecinos 'n_neighbors')
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = knn_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (KNN):", accuracy)
print("Matriz de confusión (KNN):\n", conf_matrix)

Accuracy (KNN): 0.9812206572769953
Matriz de confusión (KNN):
 [[333   1   0]
 [  7  46   0]
 [  0   0  39]]

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [ ]:
#ENTRENAR MODELO CON KNN

from sklearn.neighbors import KNeighborsClassifier

# Dividir los datos en conjuntos de entrenamiento y prueba (70/30)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo KNN (considera ajustar el número de vecinos 'n_neighbors')
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = knn_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (KNN):", accuracy)
print("Matriz de confusión (KNN):\n", conf_matrix)

Accuracy (KNN): 0.9764890282131662
Matriz de confusión (KNN):
 [[495   3   0]
 [ 12  72   0]
 [  0   0  56]]

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

#ENTRENAMIENTO CON LR

In [ ]:
#Entrenamiento del modelo con LR 80/20

from sklearn.linear_model import LogisticRegression

# Dividir los datos en conjuntos de entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo de regresión logística
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = lr_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (Logistic Regression):", accuracy)
print("Matriz de confusión (Logistic Regression):\n", conf_matrix)

Accuracy (Logistic Regression): 0.9906103286384976
Matriz de confusión (Logistic Regression):
 [[334   0   0]
 [  4  49   0]
 [  0   0  39]]

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
#Entrenamiento del modelo con LR

from sklearn.linear_model import LogisticRegression

# Dividir los datos en conjuntos de entrenamiento y prueba (70/30)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo de regresión logística
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = lr_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (Logistic Regression):", accuracy)
print("Matriz de confusión (Logistic Regression):\n", conf_matrix)

Accuracy (Logistic Regression): 0.9858934169278997
Matriz de confusión (Logistic Regression):
 [[496   2   0]
 [  7  77   0]
 [  0   0  56]]

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

#ENTRENAMIENTO CON RANDOM FOREST

In [ ]:
# Entrenamiento del modelo con random forest

from sklearn.ensemble import RandomForestClassifier

# Dividir los datos en conjuntos de entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=random_state)  # Ajusta n_estimators según sea necesario
rf_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = rf_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (Random Forest):", accuracy)
print("Matriz de confusión (Random Forest):\n", conf_matrix)

<ipython-input-124-149210d2c9b1>:31: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train, y_train)

Accuracy (Random Forest): 0.9835680751173709
Matriz de confusión (Random Forest):
 [[334   0   0]
 [  7  46   0]
 [  0   0  39]]

In [ ]:
# Dividir los datos en conjuntos de entrenamiento y prueba (70/30)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=random_state)  # Ajusta n_estimators según sea necesario
rf_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = rf_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (Random Forest):", accuracy)
print("Matriz de confusión (Random Forest):\n", conf_matrix)

<ipython-input-126-5ba4c2643c73>:27: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train, y_train)

Accuracy (Random Forest): 0.9780564263322884
Matriz de confusión (Random Forest):
 [[496   2   0]
 [ 12  72   0]
 [  0   0  56]]

#ENTRENAMIENTO CON ÁRBOLES DE DECISIÓN

In [ ]:
# Entrenamiento del modelo con árboles de decisión

from sklearn.tree import DecisionTreeClassifier

# Dividir los datos en conjuntos de entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo de árbol de decisión
dt_model = DecisionTreeClassifier(random_state=random_state)
dt_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = dt_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (Decision Tree):", accuracy)
print("Matriz de confusión (Decision Tree):\n", conf_matrix)

Accuracy (Decision Tree): 0.9765258215962441
Matriz de confusión (Decision Tree):
 [[330   4   0]
 [  6  47   0]
 [  0   0  39]]

In [ ]:
# Dividir los datos en conjuntos de entrenamiento y prueba (70/30)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=random_state)

#------------------------------------------------------
# normalizo los datos con las mismas variables para comparar el efecto de la normalización en el aprendizaje.

# Crear un objeto StandardScaler para normalizar los datos de entrenamiento
scaler1 = StandardScaler()

# Ajustar el scaler y transformar X_train
scaler1.fit(X_train)
X_train = scaler1.transform(X_train)

# Crear un objeto StandardScaler separado para normalizar los datos de prueba
scaler2 = StandardScaler()

# Ajustar el scaler y transformar X_test
scaler2.fit(X_test)
X_test = scaler1.transform(X_test)

# Mostrar el conjunto de características de prueba normalizado (X_test)
#print(X_test)
#--------------------------------------------------------

# Crear y entrenar el modelo de árbol de decisión
dt_model = DecisionTreeClassifier(random_state=random_state)
dt_model.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = dt_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy (Decision Tree):", accuracy)
print("Matriz de confusión (Decision Tree):\n", conf_matrix)

Accuracy (Decision Tree): 0.9749216300940439
Matriz de confusión (Decision Tree):
 [[494   4   0]
 [ 12  72   0]
 [  0   0  56]]